import { ClientLayout } from "@/components/ClientLayout";
import { ContainerSmoothScroll } from "@/components/containers/ContainerSmoothScroll";
import type { Metadata } from "next";
import { Instrument_Sans, Inter } from "next/font/google";
import { CursorProvider } from "./CursorProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${instrumentSans.variable} antialiased`}
      >
        <CursorProvider>
          <ContainerSmoothScroll>
            <ClientLayout>{children}</ClientLayout>
          </ContainerSmoothScroll>
        </CursorProvider>
      </body>
    </html>
  );
}
